// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $index from "./routes/index.tsx";
import * as $projects from "./routes/projects.tsx";
import * as $mobileMenu from "./islands/mobileMenu.tsx";
import * as $themeToggle from "./islands/themeToggle.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
	routes: {
		"./routes/_app.tsx": $_app,
		"./routes/about.tsx": $about,
		"./routes/index.tsx": $index,
		"./routes/projects.tsx": $projects,
	},
	islands: {
		"./islands/mobileMenu.tsx": $mobileMenu,
		"./islands/themeToggle.tsx": $themeToggle,
	},
	baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
