// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $contact from "./routes/contact.tsx";
import * as $index from "./routes/index.tsx";
import * as $projects from "./routes/projects.tsx";
import * as $thanks from "./routes/thanks.tsx";
import * as $mobileMenu from "./islands/mobileMenu.tsx";
import * as $theme from "./islands/theme.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
	routes: {
		"./routes/_404.tsx": $_404,
		"./routes/_500.tsx": $_500,
		"./routes/_app.tsx": $_app,
		"./routes/about.tsx": $about,
		"./routes/contact.tsx": $contact,
		"./routes/index.tsx": $index,
		"./routes/projects.tsx": $projects,
		"./routes/thanks.tsx": $thanks,
	},
	islands: {
		"./islands/mobileMenu.tsx": $mobileMenu,
		"./islands/theme.tsx": $theme,
	},
	baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
