name: Deploy to GitHub Pages
uses: JamesIves/github-pages-deploy-action@v4.6.3

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build
        run: deno task lume:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site